version: '3.1'

services:

  mongo:
    container_name: poll-app-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017

  redis:
   image: redis:latest
   restart: always
   ports:
    - "6379:6379"
